version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress-app
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD:-changeme}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - app-frontend
      - db-backend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=app-frontend"

      # HTTP Router
      - "traefik.http.routers.wordpress.entrypoints=web"
      - "traefik.http.routers.wordpress.rule=Host(`blog.${DOMAIN}`)"
      - "traefik.http.routers.wordpress.middlewares=https-redirect@file"

      # HTTPS Router
      - "traefik.http.routers.wordpress-secure.entrypoints=websecure"
      - "traefik.http.routers.wordpress-secure.rule=Host(`blog.${DOMAIN}`)"
      - "traefik.http.routers.wordpress-secure.tls=true"
      - "traefik.http.routers.wordpress-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.wordpress-secure.middlewares=security-chain@file"

      # Service
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"

  wordpress-db:
    image: mariadb:10.11
    container_name: wordpress-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${WP_DB_ROOT_PASSWORD:-rootchangeme}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${WP_DB_PASSWORD:-changeme}
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - db-backend

volumes:
  wordpress_data:
  wordpress_db:

networks:
  app-frontend:
    external: true
  db-backend:
    external: true