version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    networks:
      - traefik-frontend
      - traefik-management
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-frontend"

      # HTTP Router
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)"
      - "traefik.http.routers.portainer.middlewares=https-redirect@file"

      # HTTPS Router
      - "traefik.http.routers.portainer-secure.entrypoints=websecure"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.${DOMAIN}`)"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.tls.certresolver=le-dns"
      - "traefik.http.routers.portainer-secure.middlewares=security-chain@file"

      # Service - Portainer runs on port 9000
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

  # Optional: Portainer Agent for managing remote endpoints
  portainer-agent:
    image: portainer/agent:latest
    container_name: portainer-agent
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - traefik-management
    ports:
      - "9001:9001"

volumes:
  portainer_data:

networks:
  traefik-frontend:
    external: true
  traefik-management:
    external: true